### ISSUE TITLE
API response unsuccessful throw IlleagalStateException

### ISSUE THREAD

**Issue by hoikin** [AfterShip/aftership-sdk-java#18]
If the API response is not successful, the respone.body() is called twice so the Exception is thrown as below:

![image](https://user-images.githubusercontent.com/8100376/107300417-74baf880-6ab4-11eb-8ccb-53ca2f91ff88.png)

![image](https://user-images.githubusercontent.com/8100376/107300449-81d7e780-6ab4-11eb-89f2-a7f2446b203b.png)

**Comment by xugenfa** [comment]
will fix it later, thank u.

**Comment by Bossa573** [comment]
Hello @hoikin , please verify the latest version 2.0.8, 
feel free to reopen the issue if the bug still exists.
