### ISSUE TITLE
AftershipOption - Unable to resolve host 'api.aftership.com'

### ISSUE THREAD

**Issue by andreii-sp** [AfterShip/aftership-sdk-java#22]
When creating the `aftership` object my `AftershipOptions()` doesn't take a `String` as parameter.

I keep getting `UnknownHostException: Unable to resolve host "api.aftership.com"`. 

Seems that the SDK version is not consistent with the current Documentation.

**Comment by Bossa573** [comment]
"if you got unable to resolve host" error, probably you might want to check if you can connect to api.aftership.com on your host first, or can simply visit `https://api.aftership.com/` and see if you got any response on the browser
