### ISSUE TITLE
Missing NewTracking.shipment_tags

### ISSUE THREAD

**Issue by jmisur** [AfterShip/aftership-sdk-java#55]
The [Tracking API](https://www.aftership.com/docs/tracking/9870f0fa51370-create-a-tracking) supports sending tracking along with `shipment_tags`, however in [NewTracking](https://github.com/AfterShip/aftership-sdk-java/blob/master/aftership-sdk/src/main/java/com/aftership/sdk/model/tracking/NewTracking.java) object no such field exists. Please add it.

**Comment by liguangbo** [comment]
Okay, let's schedule and add this field.

**Comment by jmisur** [comment]
Thanks. Actually the field is also missing from [GetTrackingsParams](https://github.com/AfterShip/aftership-sdk-java/blob/master/aftership-sdk/src/main/java/com/aftership/sdk/model/tracking/GetTrackingsParams.java) for [GET /trackings](https://www.aftership.com/docs/tracking/ce171c8e31139-get-trackings) call.

Also, I think the field is buggy. When I tried using this field to lookup trackings with your API Docs request tester, it yielded weird results.

1. Lookup for trackings when at least 1 tracking has the shipment_tag (even it was if deleted): returns the correctly filtered trackings.
	```
	curl --request GET \
	  --url 'https://api.aftership.com/v4/trackings?shipment_tags=my_existing_tag' \
	  --header 'Content-Type: application/json' \
	  --header 'as-api-key: token'
	```
2. Lookup for trackings where no tracking has the corresponding shipment_tag (not even a deleted one): returns _all_ trackings.
	```
	curl --request GET \
	  --url 'https://api.aftership.com/v4/trackings?shipment_tags=nonexistent' \
	  --header 'Content-Type: application/json' \
	  --header 'as-api-key: token'
	```
I believe the 2. should return no trackings as the filter asks for trackings with the specific shipment tags, and if no such tracking exists, it should return empty list.

**Comment by liguangbo** [comment]
@jmisur We have already supported shipment_tags in version 2.1.11.  And we need to investigate the issue with the GetTrackings API.
