### ISSUE TITLE
Proper structure (packages) and Maven/Gradle based build with an artifact?

### ISSUE THREAD

**Issue by uded** [AfterShip/aftership-sdk-java#7]
Is there any possibility that someone will organize this project according to Java guidelines? I mean a package called "Classes" it's a bit of a surprise...

Additionally, a nice artifact placed in maven repo would be so much appreciated!

**Comment by Bossa573** [comment]
sorry for the late response, the sdk structure has been modified and this issue and related PR should be no longer valid, hence will close this issue first, please feel free to create new issues if needed
